---
- name: Load OS-specific variables
  ansible.builtin.include_vars: "{{ item }}"
  with_first_found:
    - files:
        - "{{ ansible_os_family }}.yml"
      paths:
        - "{{ role_path }}/vars"

- import_tasks: 01_install.yml
- import_tasks: 02_configure.yml
- import_tasks: 03_db_user.yml
