version: "3.9"

networks:
  wp-net:
    external: true
    name: wp-net

volumes:
  wp-db:
  wp-data:

services:
  db:
    image: mysql:8.0
    container_name: wp-db
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wpuser
      MYSQL_PASSWORD: wppass
      MYSQL_ROOT_PASSWORD: rootpass
    volumes:
      - wp-db:/var/lib/mysql
    networks:
      - wp-net
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -prootpass || exit 1"]
      interval: 10s
      retries: 10

  wordpress:
    image: wordpress:latest
    container_name: wp
    depends_on:
      db:
        condition: service_healthy
    environment:
      WORDPRESS_DB_HOST: wp-db:3306
      WORDPRESS_DB_USER: wpuser
      WORDPRESS_DB_PASSWORD: wppass
      WORDPRESS_DB_NAME: wordpress
    ports:
      - "8080:80"
    volumes:
      - wp-data:/var/www/html
      - ./apache/conf.d:/etc/apache2/conf-enabled:ro
    networks:
      - wp-net
