apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-wp
  namespace: lesson21
spec:
  accessModes: [ "ReadWriteOnce" ]
  resources:
    requests:
      storage: 10Gi
  storageClassName: local-storage
  volumeName: pv-wp-local
