apiVersion: v1
kind: Service
metadata:
  name: wordpress
  namespace: lesson21
spec:
  selector:
    app: wordpress
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30080
    name: http
  type: NodePort
