apiVersion: v1
kind: Pod
metadata:
  name: ab-load
  namespace: lesson21
  labels:
    app: ab-load
spec:
  restartPolicy: Never
  containers:
  - name: ab
    image: alpine:3.19
    command:
      - /bin/sh
      - -c
      - |
        apk add --no-cache apache2-utils >/dev/null && \
        echo "Running ab..." && \
        ab -n 50000 -c 200 http://wordpress.lesson21.svc.cluster.local/ && \
        echo "Done"
